version: "3.10"
   
services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6432:5432"
  web:
    container_name: web
    build: .
    command: /start-sh
    volumes:
      - ./blog:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres_db